[build]
buildpacks = ["https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"]
builder = "nixpacks"

[build.nixpacksConfig]
[build.nixpacksConfig.build]
cmds = [
  "npm install --no-workspaces --legacy-peer-deps",
  "npm run build"
]

[deploy]
startCommand = "npm start"