[build]
builder = "nixpacks"

[build.nixpacksConfig]
[build.nixpacksConfig.phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg"]

[build.nixpacksConfig.phases.build]
cmds = [
  "npm install --no-workspaces --legacy-peer-deps",
  "npm run build"
]

[deploy]
startCommand = "npm start"